### ISSUE TITLE
Is there an error when calculating recall_precision_accuracy_f1?

### ISSUE THREAD

**Issue by qiyea** [linfengYang/BitcnNILM#1]
At line 277 of file seq2point.py, when you use the function nm.recall_precision_accuracy_f1, the first parameter is "ground_truth " and the second parameter is "prediction". This is the opposite of the definition of the function on line 283 of the file nilm_metric.py

**Comment by linfengYang** [comment]
@qiyea Hello, you just need to follow the order of definition and we'll upload a new version with clearer comments!

**Comment by qiyea** [comment]
> @qiyea Hello, you just need to follow the order of definition and we'll upload a new version with clearer comments!

OK Thanks！

**Comment by linfengYang** [comment]
@qiyea I have updated this code. After the change, F1, Accuracy, MAE, SAE remained the same, but the value of Precision and Recall were swapped.

**Comment by qiyea** [comment]
OK. Thanks for your reply！
